### ISSUE TITLE
[Suggestion] Preserve user data against update 42seoul Policy for outer circle

### ISSUE THREAD

**Issue by hochan222** [JaeSeoKim/badge42#64]
Outer circles can no longer receive 42API information after February. 

I would like to preserve information about this.

**Comment by JaeSeoKim** [comment]
It seems to be a very important issue.

The best way is to build a DB in badge42 so that it can continue to have information, but I'd like to suggest the following method because we can't proceed right now.

- The response value of badge42 is the svg image. There is a way to visit the API in person and store the response values and use them statically.
